name: infra_deploy

trigger: none

variables:
  - name: WORK_DIR
    value: '$(System.DefaultWorkingDirectory)/environment'
  - name: SER_CONN
    value: 'Empire_Operations_Agent_SC'
    

parameters:
  - name: infraenv
    displayName: environment
    type: string
    default: preprod
    values:
      - preprod
      - prod

pool: 
 name: Empire_Operations_Agent


stages:
 - stage: terraforminit
   jobs:
     - job: terraforminit
       steps:
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(WORK_DIR)/${{ parameters.infraenv }}
            backendServiceArm: $(SER_CONN)
            backendAzureRmOverrideSubscriptionID: 'b4461466-1e6b-4be2-bb70-1e96a72a41c8'
            backendAzureRmResourceGroupName: 'Empire_Operation_rg'
            backendAzureRmStorageAccountName: 'empireoperationstg'
            backendAzureRmContainerName: 'empirecontainer'
            backendAzureRmKey: 'infradev.tfstate'

        - task: TerraformTask@5
          displayName: validation
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)'

        - task: DownloadSecureFile@1
          displayName: tfvars download
          name: tfvars
          inputs:
            secureFile: 'terraform-${{ parameters.infraenv }}.tfvars'

        
        - task: PowerShell@2
          displayName: copy file
          inputs:
            targetType: 'inline'
            script: cp "$(tfvars.secureFilePath)" "$(WORK_DIR)/${{ parameters.infraenv }}"

        - task: TerraformTask@5
          displayName: plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(WORK_DIR)/${{ parameters.infraenv }}'
            commandOptions: '-var-file=terraform-${{ parameters.infraenv }}.tfvars'
            environmentServiceNameAzureRM: 'Empire_Operations_Agent_SC'

 - stage: securityscanning
   jobs:
     - job: tfscan
       steps:
       - task: tfsec@1
         displayName: tfscanning
         inputs:
           version: 'v1.26.0'
           dir: '$(WORK_DIR)'

       - task: PowerShell@2
         displayName: checkov scanning
         inputs:
           targetType: 'inline'
           script: 'checkov -d $(System.DefaultWorkingDirectory) -o junitxml > checkov-scan.xml'

       - task: PublishTestResults@2
         inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: 'checkov-scan.xml'
          testRunTitle: 'checkovscan'